#include<stdio.h>
#include<iostream.h>
#include<conio.h>
void main()
{
	 int ron,c1,c2,c3,c4,c5,c6,total;
	 clrscr();
	 cout<<"\nenter your roll no=>";
	 cin>>ron;
	 cout<<"\nEnter your c1 mark=>";
	 cin>>c1;
	 cout<<"\nEnter your c2 mark=>";
	 cin>>c2;
	 cout<<"\nEnter your c3 mark=>";
	 cin>>c3;
	 cout<<"\nENTER YOUR C4 MARK=>";
	 cin>>c4;
	 cout<<"\nEnter Your c5 Mark=>";
	 cin>>c5;
	 cout<<"\nEnter Your c6 Mark=.";
	 cin>>c6;

	 ~
	 total=c1+c2+c3;
	 cout<<"total="<<total;
	 getch();
}
